platform/ATSAMR21-XPRO/los_bsp_adapter.c
platform/ATSAMR21-XPRO/los_bsp_clock.c
platform/ATSAMR21-XPRO/los_bsp_key.c
platform/ATSAMR21-XPRO/los_bsp_led.c
platform/ATSAMR21-XPRO/los_bsp_uart.c
projects/ATSAMR21-XPRO-KEIL/HuaweiLiteOS.uvoptx
projects/ATSAMR21-XPRO-KEIL/HuaweiLiteOS.uvprojx

Add ATSAMR21-XPRO board support to Huawei LiteOS
modify platform/ATSAMR21-XPRO dir.
modify projects/ATSAMR21-XPRO-KEIL dir.
Close #121

feat(null):add ATSAMR21-XPRO board support

---

kernel/cpu/arm/cortex-m0+/los_dispatch_iar.s
kernel/cpu/arm/cortex-m0/los_hw.c
kernel/cpu/arm/cortex-m0/los_hwi.c
kernel/cpu/arm/cortex-m0/los_hwi.h
projects/LPC824_LITE_KEIL/HuaweiLiteOS.uvoptx
projects/LPC824_LITE_KEIL/HuaweiLiteOS.uvprojx

Some macro name was error defined in CM0,fix it.
Close #119

feat(cortex-m0):fix some macro name to fit CM0

---

kernel/base/ipc/los_event.c

fix event bug

---

kernel/base/ipc/los_event.c

 fix event bug 

---

components/connectivity/agent_tiny/lwm2m_client/object_access_control.c
components/connectivity/agent_tiny/lwm2m_client/object_comm.h
components/connectivity/lwm2m/core/internals.h
components/connectivity/lwm2m/core/management.c
components/connectivity/lwm2m/core/objects.c
components/connectivity/lwm2m/core/observe.c
components/fota/ota/crc.c

add acc obj to lwm2m
add auth code of acc object

add acc object to lwm2m protocal

---

components/connectivity/agent_tiny/examples/agent_tiny_cmd_ioctl.c
components/connectivity/agent_tiny/lwm2m_client/agenttiny.h
components/connectivity/agent_tiny/lwm2m_client/object_location.c

add the implementation of the location object

add the implementation of the location object

---

targets/STM32F429IGTx_FIRE/Hardware/Src/hal_rng.c

fix bug of RNG

---

components/net/lwip-2.0.3/src/include/lwip/opt.h

randomize UDP and TCP initial port for every reboot.

randomize UDP and TCP initial port.

---

components/connectivity/agent_tiny/lwm2m_client/platform_adapter.c
components/connectivity/lwm2m/core/liblwm2m.c
components/connectivity/lwm2m/core/liblwm2m.h

Randomize coap mid  for every reboot.

Randomize coap mid

---

components/connectivity/lwm2m/core/observe.c

fix bug of mutex in observe.c

---

components/fota/ota/ota.c
components/fota/ota/ota.h
components/fota/ota/ota_default.c
components/fota/ota/ota_default.h
components/fota/ota/ota_errno.h
targets/STM32F429IGTx_FIRE/GCC/Makefile
targets/STM32F429IGTx_FIRE/GCC/STM32F429IGTx_LiteOS_Bootloader.ld
targets/STM32F429IGTx_FIRE/Src/fota_port.c

fix bug of update process in ota_default.c

fix bug of update process in ota_default.c

---

components/fota/fota_package_storage_device/fota_firmware_writer.c
components/net/lwip_port/OS/ethernetif.c
targets/STM32F429IGTx_FIRE/Src/fota_port.c
targets/STM32F429IGTx_FIRE/Src/sys_init.c

clear pclint

---

components/connectivity/at_frame/at_api_interface.c
components/connectivity/at_frame/at_api_interface.h
components/connectivity/at_frame/at_hal.c
components/connectivity/at_frame/at_hal.h
components/connectivity/at_frame/atadapter.c
components/connectivity/at_frame/atadapter.h
drivers/devices/gprs/sim900a.c
drivers/devices/gprs/sim900a.h
drivers/devices/nb/bc95.c
drivers/devices/nb/bc95.h
drivers/devices/wifi/esp8266.c
drivers/devices/wifi/esp8266.h
targets/STM32F429IGTx_FIRE/Src/main.c

2. add deinit function for at_framework
3. fix main(), when use esp8266 and sim900a, need to run agent_tiny_entry(), while bc95 not.

1. add license

---

components/connectivity/agent_tiny/firmware_update/firmware_update.c
components/connectivity/agent_tiny/lwm2m_client/agenttiny.c
components/connectivity/agent_tiny/lwm2m_client/atiny_update_info.c
components/connectivity/agent_tiny/lwm2m_client/object_firmware.c
components/connectivity/lwm2m/core/observe.c

clear codex

---

components/fota/ota/ota_default.c

fix bug of image integrity check

fix bug of image integrity check

---

components/fota/ota/ota_default.c
components/fota/ota/ota_default.h
targets/STM32F429IGTx_FIRE/Inc/board.h
targets/STM32F429IGTx_FIRE/Src/board.c

fix bug of bootloader

---

components/connectivity/agent_tiny/examples/agent_tiny_demo.c
components/connectivity/agent_tiny/lwm2m_client/agenttiny.c
components/connectivity/agent_tiny/lwm2m_client/fota/atiny_fota_manager.c
components/connectivity/agent_tiny/lwm2m_client/fota/atiny_fota_manager.h
components/connectivity/agent_tiny/lwm2m_client/fota/atiny_fota_state.c
components/connectivity/agent_tiny/lwm2m_client/fota/atiny_fota_state.h
components/connectivity/agent_tiny/lwm2m_client/object_firmware.c
components/connectivity/lwm2m/core/liblwm2m.h
components/connectivity/lwm2m/core/observe.c
components/fota/fota_package_storage_device/fota_package_head.h
targets/Cloud_STM32F429IGTx_FIRE/GCC/Makefile

1.add firmware state notify ack
2.modify fota macro for fota feature.

state notify ack and fota macro

---

components/connectivity/at_frame/atadapter.c
components/security/mbedtls/mbedtls_port/dtls_interface.c
drivers/devices/gprs/sim900a.c

2. fix dtls communication failed in use sim900a

1. fix 200ms delay in at_write

---

components/fs/spiffs/los_spiffs.c
components/fs/vfs/los_vfs.c

fixed an silly bug in los_spiffs.c and some other minor updates

fixed an silly bug in los_spiffs.c and some other minor updates

---

components/connectivity/agent_tiny/lwm2m_client/object_security.c
components/connectivity/lwm2m/core/liblwm2m.c
components/connectivity/lwm2m/core/observe.c
components/fota/ota/ota_default.c
components/security/mbedtls/mbedtls_port/dtls_interface.c
targets/Cloud_STM32F429IGTx_FIRE/Src/fota_port.c

1、消除内存泄漏隐患
2、规避空指针错误
3、消除编译警告及memcheck报的变量未初始化错误

 fix some bugs of agenttiny and so on.

---

components/connectivity/at_frame/atadapter.c
drivers/devices/gprs/sim900a.c
drivers/devices/wifi/esp8266.c

1、修复AT模块的内存泄漏和地址越界的bug
2、在野火工程下测试编译通过，注：at_hal.c默认未加入工程，本次保持现状未做修改

fix memory-leak and cross-border bugs of at module.

---

drivers/devices/gprs/sim900a.c
drivers/devices/wifi/esp8266.c
targets/Cloud_STM32F429IGTx_FIRE/EWARM/Huawei_LiteOS.ewp
targets/Cloud_STM32F429IGTx_FIRE/MDK-ARM/Huawei_LiteOS.uvoptx
targets/Cloud_STM32F429IGTx_FIRE/MDK-ARM/Huawei_LiteOS.uvprojx

1、在IAR、Keil、GCC环境下编译测试通过
2、IAR和Keil工程中加入at_hal.c文件，并修复其他编译错误
3、GCC下修复编译告警项

fix bug(call before declaration) of at module and so on.

---

targets/Cloud_NXP51U68/MDK-ARM/Huawei_LiteOS.uvoptx
targets/Cloud_NXP51U68/MDK-ARM/Huawei_LiteOS.uvprojx
targets/Cloud_NXP51U68/OS_CONFIG/los_mbedtls_config.h
targets/Cloud_NXP51U68/OS_CONFIG/los_mbedtls_config_psk.h
targets/Cloud_NXP51U68/OS_CONFIG/lwipopts.h
targets/Cloud_NXP51U68/OS_CONFIG/target_config.h
targets/Cloud_NXP51U68/user/agent_tiny_demo.c
targets/Cloud_NXP51U68/user/atcmd.c
targets/Cloud_NXP51U68/user/ethernetif.c
targets/Cloud_NXP51U68/user/main.c
targets/Cloud_NXP51U68/user/osport.c
targets/Cloud_NXP51U68/user/ppp_nxp.c
targets/Cloud_NXP51U68/user/ring.c
targets/Cloud_NXP51U68/user/ring.h

1,修改了NXPM0+的配置，降低RAM和ROM的消耗（全栈使用RAM<32KB,ROM 140KB），该版本使用SPI以太网
2,该工程下一步支持PPPOS拨号模式

optimize the nxp51u68 project resources

---

components/connectivity/agent_tiny/lwm2m_client/agenttiny.c
components/connectivity/agent_tiny/lwm2m_client/fota/atiny_fota_manager.c
drivers/devices/wifi/marvell/wifi.c
drivers/devices/wifi/marvell/wpa.c

clean up pclint

---

targets/Cloud_NXP51U68/MDK-ARM/Huawei_LiteOS.uvoptx
targets/Cloud_NXP51U68/MDK-ARM/Huawei_LiteOS.uvprojx
targets/Cloud_NXP51U68/pppport/ppp.c
targets/Cloud_NXP51U68/user/main.c
targets/Cloud_NXP51U68/user/uart.c
targets/Cloud_STM32F429IGTx_FIRE/MDK-ARM/Huawei_LiteOS.uvoptx
targets/Cloud_STM32F429IGTx_FIRE/MDK-ARM/Huawei_LiteOS.uvprojx
targets/Cloud_STM32L431RxTx_IoTClub/MDK-ARM/STM32L431RxTx.uvoptx
targets/Cloud_STM32L431RxTx_IoTClub/MDK-ARM/STM32L431RxTx.uvprojx
targets/Cloud_wifi_STM32F767ZI_NUCLEO/Src/fota_port.c
targets/Standard_FRDM_KW41Z/EWARM/Huawei_LiteOS.ewp
targets/Standard_IMXRT1052_FIRE/project/mdk/HuaweiLiteOS.uvoptx
targets/Standard_IMXRT1052_FIRE/project/mdk/HuaweiLiteOS.uvprojx
targets/Standard_STM32F103RB_NUCLEO/EWARM/Huawei_LiteOS.ewp
targets/Standard_STM32F746ZG_NUCLEO/EWARM/Huawei_LiteOS.ewp

resolve target compilation warning partly

fix compilation warning

---

targets/Cloud_STM3210E_EVAL/MDK-ARM/Huawei_LiteOS.uvoptx
targets/Cloud_STM3210E_EVAL/MDK-ARM/Huawei_LiteOS.uvprojx
targets/Cloud_wifi_STM32F429ZI_NUCLEO/EWARM/Huawei_LiteOS.ewd
targets/Cloud_wifi_STM32F429ZI_NUCLEO/EWARM/Huawei_LiteOS.ewp
targets/Cloud_wifi_STM32F429ZI_NUCLEO/GCC/Makefile
targets/Cloud_wifi_STM32F429ZI_NUCLEO/MDK-ARM/Huawei_LiteOS.uvoptx
targets/Cloud_wifi_STM32F429ZI_NUCLEO/MDK-ARM/Huawei_LiteOS.uvprojx

1、commandline和esp8266目录结构调整，因此跟新目标板工程文件

update the project nucleo-f429zi and stm3210e_eval.

---

drivers/devices/gprs/sim900a.c
drivers/devices/wifi/esp8266/esp8266.c

1、修复deinit时的段错误，应该判断at.linkid不为NULL

fix bug of at module.

---

components/connectivity/at_frame/atadapter.c

fix cloud_cmd_matching for data_handler

---

components/security/mbedtls/mbedtls_port/los_mbedtls_config.h
components/security/mbedtls/mbedtls_port/los_mbedtls_config_psk.h

add comments on los_mbedtls_config of #if 0

add comments on los_mbedtls_config of #if 0

---

drivers/devices/wifi/esp8266_anylink_spi/Cortex-M3_lib/M8266_WIFI_SPI.c
drivers/devices/wifi/esp8266_anylink_spi/Cortex-M4_lib/M8266_WIFI_SPI.c
drivers/devices/wifi/esp8266_anylink_spi/Cortex-M7_lib/M8266_WIFI_SPI.c

delete useless #if 0

---

components/fota/ota/ota_default.c
targets/Cloud_STM3210E_EVAL/Inc/board.h
targets/Cloud_STM3210E_EVAL/Src/board.c
targets/Cloud_STM32F429IGTx_FIRE/Inc/board.h
targets/Cloud_STM32F429IGTx_FIRE/Src/board.c
targets/Cloud_STM32L431RxTx_IoTClub/Inc/board.h
targets/Cloud_STM32L431RxTx_IoTClub/Src/board.c
targets/Cloud_wifi_STM32F429ZI_NUCLEO/Inc/board.h
targets/Cloud_wifi_STM32F429ZI_NUCLEO/Src/board.c
targets/Cloud_wifi_STM32F767ZI_NUCLEO/Inc/board.h
targets/Cloud_wifi_STM32F767ZI_NUCLEO/Src/board.c

adjust interface in board.h

---

targets/Cloud_STM3210E_EVAL/Hardware/Src/hal_sd.c
targets/Cloud_STM3210E_EVAL/Src/w5500_conf.c

1) fix interrupt receive bug
2) fix compilation warning

fix bug of wiznet

---

components/connectivity/agent_tiny/examples/agent_tiny_cmd_ioctl.c
components/connectivity/agent_tiny/examples/agent_tiny_demo.c
components/connectivity/agent_tiny/lwm2m_client/agenttiny.c
components/connectivity/agent_tiny/lwm2m_client/agenttiny.h
components/connectivity/agent_tiny/lwm2m_client/connection.c
components/connectivity/agent_tiny/lwm2m_client/connection.h
components/connectivity/agent_tiny/lwm2m_client/object_security.c
components/connectivity/agent_tiny/lwm2m_client/util_timer.c
components/connectivity/agent_tiny/lwm2m_client/util_timer.h
components/connectivity/agent_tiny/osadapter/atiny_socket.c
components/connectivity/at_frame/at_api_interface.c
components/connectivity/at_frame/at_api_interface.h
components/connectivity/at_frame/atadapter.c
components/connectivity/at_frame/atadapter.h
components/connectivity/lwm2m/core/bootstrap.c
components/connectivity/lwm2m/core/er-coap-13/er-coap-13.h
components/connectivity/lwm2m/core/internals.h
components/connectivity/lwm2m/core/liblwm2m.c
components/connectivity/lwm2m/core/liblwm2m.h
components/connectivity/lwm2m/core/liblwm2m_api.h
components/connectivity/lwm2m/core/objects.c
components/security/mbedtls/mbedtls_port/dtls_interface.c
components/security/mbedtls/mbedtls_port/dtls_interface.h
drivers/devices/nb/bc95.c
drivers/devices/nb/bc95.h
targets/Cloud_STM32F429IGTx_FIRE/Src/at_hal.c
targets/Cloud_STM32F429IGTx_FIRE/Src/main.c

1.add support for server initiated boostrap.
2. add delay for retrying register and boostrap,and multimupl retry according the bootstrap mode.
3. add support for dtls server
4. AT support mutiple matching strings. when error happen, it will callback immediatly
5. many bugs for nb95 for socket support

modify boostrap and at module

---

components/connectivity/sota/sota.c

fix bug of sota.c(line379)

---

components/connectivity/at_frame/atadapter.c
components/connectivity/at_frame/atadapter.h

null point for at_listener

---

components/connectivity/at_frame/atadapter.c

solve bugs of at frame in at_recv_task

---

components/ota/flag_operate/flag_manager.c
components/ota/flag_operate/flag_manager.h
components/ota/flag_operate/upgrade_flag.c
components/ota/flag_operate/upgrade_flag.h
include/fota/hwpatch_errno.h
include/fota/recover_image.h

add huawei license

---

components/ota/flag_operate/upgrade_flag.c
components/ota/flag_operate/upgrade_flag.h
targets/Cloud_STM32F429IGTx_FIRE/Src/bootloader_recover.c

modify recover verify implementation

modify recover verify implementation

---

include/fota/recover_image.h

add arg name in interface and add comment on recover_upgrade_type_e

add arg name in interface and add comment on recover_upgrade_type_e

---

demos/fs/fatfs_demo.c
demos/fs/fs_common.c
demos/fs/fs_common.h
demos/fs/jiffs_demo.c
demos/fs/spiffs_demo.c
targets/Cloud_STM32F429IGTx_FIRE/GCC/Makefile
targets/Cloud_STM32F429IGTx_FIRE/GCC/config.mk
targets/Cloud_STM32F429IGTx_FIRE/GCC/config_demos/config_bootloader.mk
targets/Cloud_STM32F429IGTx_FIRE/GCC/config_demos/config_lwm2m.mk
targets/Cloud_STM32F429IGTx_FIRE/GCC/config_demos/config_mqtt.mk
targets/Cloud_STM32F429IGTx_FIRE/GCC/config_demos/config_sota.mk
targets/Cloud_STM32F429IGTx_FIRE/GCC/config_demos/config_sota_without_checksum.mk
targets/Cloud_STM32F429IGTx_FIRE/Src/board.c
targets/Cloud_STM32F429IGTx_FIRE/Src/main.c

optimize fs demo and modify for board.c warning

optimize fs demo and modify for board.c warning

---

tests/test_sota/sota_test.c
tests/test_sota/sota_test.h

modify the interface test

---

components/net/at_device/emtc_bg36/bg36.c

Fixed codedex

---

components/connectivity/agent_tiny/atiny_lwm2m/agenttiny.c
components/connectivity/agent_tiny/atiny_lwm2m/object_server.c

add parameter checking for agent tiny module.

add parameter checking for agent tiny module.

---

targets/Cloud_STM32F429IGTx_FIRE/GCC/Makefile_Sota

add separate sota makefile to build libsota.lib, which will include libhwpatch.a as well

add separate sota makefile to build libsota.a

---

demos/sensor/timer_demo.c
include/uds/uds_gpio.h
include/uds/uds_timer.h
targets/STM32L476RGTx_Six_Square/Inc/stm32l4xx_hal_conf.h
targets/STM32L476RGTx_Six_Square/MDK-ARM/Huawei_LiteOS.uvoptx
targets/STM32L476RGTx_Six_Square/MDK-ARM/Huawei_LiteOS.uvprojx
targets/STM32L476RGTx_Six_Square/Src/uds_timer.c
targets/STM32L476RGTx_Six_Square/Src/user_task.c

add timer demo.

---

components/connectivity/agent_tiny/atiny_mqtt/mqtt_client.c
include/atiny_mqtt/mqtt_client.h

delete the mqtt_deinit,make some constraint for mqtt_init and mqtt_bind.
1.delete mqtt_deinit.
2.free the resource created by mqtt_init when bind error happens.
3.add max len check for password.
4.add reinit check in mqtt_init

delete the mqtt_deinit,make some constraint for mqtt_init and mqtt_bind.

---

components/ota/sota/sota.c

Add timeout process for update status

Add timeout process for update status

---

components/ota/package/package_checksum.c

Fixed package checksum bug

---

demos/sensor/gpio_demo.c
demos/sensor/timer_demo.c
include/uds/uds_gpio.h
include/uds/uds_timer.h
targets/STM32L476RGTx_Six_Square/MDK-ARM/Huawei_LiteOS.uvoptx
targets/STM32L476RGTx_Six_Square/Src/i2c.c
targets/STM32L476RGTx_Six_Square/Src/uds_gpio.c
targets/STM32L476RGTx_Six_Square/Src/uds_timer.c
targets/STM32L476RGTx_Six_Square/Src/user_task.c

修改了install函数参数错误的问题。将gpio和timer的中断方式改为注册式。

change gpio,timer,i2c files.

---

demos/sensor/rtc_demo.c
include/uds/uds_rtc.h
targets/STM32L476RGTx_Six_Square/MDK-ARM/Huawei_LiteOS.uvoptx
targets/STM32L476RGTx_Six_Square/MDK-ARM/Huawei_LiteOS.uvprojx
targets/STM32L476RGTx_Six_Square/Src/main.c
targets/STM32L476RGTx_Six_Square/Src/rtc.c
targets/STM32L476RGTx_Six_Square/Src/user_task.c

add rtc demo.

---

tests/test_sota/sota_test.c
tests/test_sota/sota_test.h

modify sota test cases

---

unittest/components/connectivity/agent_tiny/atiny_mqtt/test_mqtt_client.cpp
unittest/components/connectivity/agent_tiny/atiny_mqtt/test_mqtt_client.h

solve mqtt test memory leak

---

components/net/at_frame/at_main.c
components/net/lwip/lwip_port/OS/ethernetif.c
components/net/lwip/lwip_port/OS/lwipopts.h
components/net/sal/atiny_socket.c
demos/agenttiny_lwm2m/agent_tiny_demo.c
demos/ipv6_client/client_demo.c
include/at_frame/at_main.h
targets/Cloud_STM32F429IGTx_FIRE/GCC/Makefile
targets/Cloud_STM32F429IGTx_FIRE/Src/sys_init.c

lwm2m support ipv6

---

demos/sensor/gpio_demo.c
include/uds/uds_gpio.h
targets/STM32L476RGTx_Six_Square/Src/uds_gpio.c

change gpio files.

---

components/connectivity/mqtt/MQTTClient-C/src/liteOS/MQTTliteos.c
components/connectivity/mqtt/MQTTClient-C/src/liteOS/MQTTliteos.h
include/atiny_mqtt/mqtt_client.h

1,move the tls data structure defined in mqtt_client.h to MQTTliteos.h
2,fix the WITH_DTLS defines to manage the code in MQTTliteos.c

FIX some unreasonable defines for mqtt (data defines and the code WITH_DTLS covers)

---

components/mqtt/Readme.md

2, fix the err for the mqtt_al_deo

1, add the readme for the mqtt
